name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Run Gem Install
      run: gem install rake --no-document
    - name: Add Packages
      run: sudo apt -y install build-essential bison git libelf-dev libelf1
    - name: Run Build
      run: rake